tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "romkatv/powerlevel10k"
brew "gh"
brew "git"
brew "git-lfs"
brew "postgresql", restart_service: true
brew "python@3.9"
brew "rbenv"
brew "task"
brew "timewarrior"
brew "tldr"
brew "zsh-syntax-highlighting"
brew "romkatv/powerlevel10k/powerlevel10k"
